/**
 * Download QPC V2 per-page fonts (p1.woff2 … p604.woff2) from Tarteel CDN.
 * Each page renders with its own font because code_v2 glyphs are page-scoped.
 *
 * Run:  npm run download:fonts
 */

import { mkdir, writeFile, stat } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const OUT_DIR = join(ROOT, 'apps', 'web', 'public', 'fonts', 'v2');
const OUT_CSS = join(ROOT, 'apps', 'web', 'src', 'styles', 'quran-fonts.css');

const CDN = 'https://static-cdn.tarteel.ai/qul/fonts/quran_fonts/v2/woff2';
const TOTAL_PAGES = 604;
const CONCURRENCY = 12;

async function exists(p: string): Promise<boolean> {
  try { await stat(p); return true; } catch { return false; }
}

async function downloadOne(pageNumber: number, force: boolean): Promise<'skipped' | 'downloaded'> {
  const out = join(OUT_DIR, `p${pageNumber}.woff2`);
  if (!force && await exists(out)) return 'skipped';
  const url = `${CDN}/p${pageNumber}.woff2`;
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
      const buf = Buffer.from(await res.arrayBuffer());
      await writeFile(out, buf);
      return 'downloaded';
    } catch (err) {
      if (attempt === 2) throw err;
      await new Promise((r) => setTimeout(r, 500 * (attempt + 1)));
    }
  }
  throw new Error('unreachable');
}

async function mapLimit<T>(items: T[], limit: number, fn: (item: T) => Promise<void>): Promise<void> {
  let cursor = 0;
  async function worker(): Promise<void> {
    while (true) {
      const i = cursor++;
      if (i >= items.length) return;
      await fn(items[i]);
    }
  }
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
}

async function main(): Promise<void> {
  const force = process.argv.includes('--force');
  await mkdir(OUT_DIR, { recursive: true });

  const pageNumbers = Array.from({ length: TOTAL_PAGES }, (_, i) => i + 1);
  let downloaded = 0;
  let skipped = 0;
  let failed = 0;

  console.log(`[fonts] target ${TOTAL_PAGES} files @ concurrency ${CONCURRENCY}${force ? ' (force)' : ''}…`);
  let progress = 0;
  await mapLimit(pageNumbers, CONCURRENCY, async (n) => {
    try {
      const r = await downloadOne(n, force);
      if (r === 'downloaded') downloaded++; else skipped++;
    } catch (err) {
      failed++;
      console.error(`[fonts] p${n}.woff2 failed:`, (err as Error).message);
    }
    progress++;
    if (progress % 50 === 0 || progress === TOTAL_PAGES) {
      console.log(`[fonts] ${progress}/${TOTAL_PAGES}`);
    }
  });

  console.log(`[fonts] done. downloaded=${downloaded} skipped=${skipped} failed=${failed}`);
  if (failed > 0) process.exit(1);

  // Emit @font-face block for all 604 pages. Browser only fetches the woff2
  // when font-family 'QPC V2 P{N}' is actually used → lazy by default.
  const lines: string[] = [
    '/* AUTO-GENERATED by scripts/download-fonts.ts — do not edit by hand.',
    ' * 604 @font-face declarations, one per Madani 15-line page.',
    ' * Use in JSX: style={{ fontFamily: `\'QPC V2 P${pageNumber}\'` }}',
    ' */',
    '',
  ];
  for (let n = 1; n <= TOTAL_PAGES; n++) {
    lines.push(
      `@font-face { font-family: 'QPC V2 P${n}'; src: url('/fonts/v2/p${n}.woff2') format('woff2'); font-display: swap; }`,
    );
  }
  await writeFile(OUT_CSS, lines.join('\n') + '\n');
  console.log(`[fonts] wrote ${OUT_CSS} (${TOTAL_PAGES} @font-face rules)`);
}

main().catch((err) => { console.error(err); process.exit(1); });
